Revert "trim security.h"
This reverts commit ae1a442f9d9599f6f46d2fe6530c7b17d53ae437.

This commit causes compile errors:

In file included from mm/mprotect.c:17:0:
include/linux/security.h: In function ‘security_real_capable’:
include/linux/security.h:1885:2: error: implicit declaration of function ‘__task_cred’ [-Werror=implicit-function-declaration]
include/linux/security.h:1885:2: warning: passing argument 2 of ‘cap_capable’ makes pointer from integer without a cast [enabled by default]
include/linux/security.h:69:12: note: expected ‘const struct cred *’ but argument is of type ‘int’
include/linux/security.h: In function ‘security_real_capable_noaudit’:
include/linux/security.h:1897:11: warning: passing argument 2 of ‘cap_capable’ makes pointer from integer without a cast [enabled by default]
include/linux/security.h:69:12: note: expected ‘const struct cred *’ but argument is of type ‘int’